Document: heaptrace
Title: Debian heaptrace Manual
Author: Aaron Esau <aaron1esau@gmail.com>
Abstract: heaptrace is a heap debugger for tracking glibc 
  heap operations in ELF64 (x86_64) binaries. Its purpose 
  is to help visualize heap operations when debugging 
  binaries or doing heap pwn.
Section: utils

Format: debiandoc-sgml
Files: /usr/share/doc/heaptrace/heaptrace.sgml.gz

Format: postscript
Files: /usr/share/doc/heaptrace/heaptrace.ps.gz

Format: text
Files: /usr/share/doc/heaptrace/heaptrace.text.gz

Format: HTML
Index: /usr/share/doc/heaptrace/html/index.html
Files: /usr/share/doc/heaptrace/html/*.html
